apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  containers:
    - image: redis
      name: redis123
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
